name: flash_cards
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  hydrated_bloc: ^11.0.0

  flutter_screenutil_plus: ^1.5.0
  flip_card: ^0.7.0

  smooth_page_indicator: ^1.2.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

  animations: ^3.0.0
  flutter_animate: ^4.5.2

  skeletonizer_plus: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true